### ISSUE TITLE
How is it going?

### ISSUE THREAD

**Issue by houjunlong** [vec2k4/vs-code-csharp-skeleton#1]
Excuse me I am a chinese , so my english is poor, Sorry!
VS Code is good,but I don't know how is it going.Except Mono,It needs others'?or...
and,words completeing needs what setting?

**Comment by vec2k4** [comment]
It's a little bit hard for me trying to understand what exactly you mean. But I will try to answer your question as I have understood it:

First you need to install VS Code. Documentation can be found here: https://code.visualstudio.com/Docs/setup

Then, install Mono as described in the ReadMe.md.

After that, clone this repository and just open the folder containing the .sln file in VS Code. 

You should have intellisense and basic debugging support for C# then.

**Comment by houjunlong** [comment]
First,thanks for your answer!
In These files,which provide the intellisense and basic debugging support?
